### ISSUE TITLE
Whitespace in the name for a "Extra Vault Folder"

### ISSUE THREAD

**Issue by sreher** [Ruoyu-Klaus/obsidian-clipper#1]
Hi Ruoyu,
really nice clipper. 
I tried around and one thing, i like, didn't work or at least I didn't manage to solve it. 
I want to put my clips in a folder with a whitespace in the name, something like "notes/080 Webclips/".
Is that possible?
Thanks.

**Comment by marwanm-dev** [comment]
Hi, How do you even specify your vault?
![image](https://github.com/Ruoyu-Klaus/obsidian-clipper/assets/90101257/ee1a409d-d548-408d-9a63-3904a8517f55)

**Comment by marwanm-dev** [comment]
Hi @sreher, How do you even specify your vault?
![image](https://github.com/Ruoyu-Klaus/obsidian-clipper/assets/90101257/ee1a409d-d548-408d-9a63-3904a8517f55)

@Ruoyu-Klaus didn't find any contact email not even on your website..

**Comment by Ruoyu-Klaus** [comment]
Hi

**Comment by Ruoyu-Klaus** [comment]
Hi all, thank you all for using 🫶 [obsidian-clipper](https://github.com/Ruoyu-Klaus/obsidian-clipper).

Sorry, I've been away from the program for a quite long time.  
Currently, it's not support for path with white space. 

It's a common need I think, 👀 I'll take a look and fix it by next Tuesday.

**Comment by Ruoyu-Klaus** [comment]
Hello, @sreher @marwanm-dev new version [v.13.6](https://github.com/Ruoyu-Klaus/obsidian-clipper/releases/tag/v1.3.6)  has been published, hope you have a fun with it. Please leave your comments if there is any feedback ;) #
